### ISSUE TITLE
Error with Search Module Report Generation

### ISSUE THREAD

**Issue by marleyjaffe** [Nuix/Search-Module#1]
Hi, 

When running the Search Module in Nuix, we are recieving an error message. The Module creates the tags frm the search module but doesn't tag the documents  or Generate the report. 
Attached, please find a txt file containing the error message we are receiving. 

Please note that the search terms that we are using contains smaller characters then the terms we have used previously. 
[SearchModuleError.txt](https://github.com/Nuix/Search-Module/files/3979889/SearchModuleError.txt)

**Comment by JuicyDragon** [comment]
Hello @marleyjaffe , sorry for the very delayed response I have been on leave for a while.

Reviewing the error, it looks like some of your searches had errors when Nuix ran them.  Search module captures the error Nuix returns and reports it in the output spreadsheet.  It appears that at least one of these error messages exceeds the 32K cell character limit, causing the reported error.

I'm considering changes that could prevent the 32K character limit error in this instance.  I'm thinking either I'll truncate the error message so that it does not exceed the character limit or have the excess characters spill over into the following cell(s).  I'm currently preferring the cell spill over approach for instances where the most relevant part of an error message may be towards the end of a long error message, so it is not lost by truncation.

**Comment by JuicyDragon** [comment]
I know it has been some time since you submit this issue, but by chance might you have the query (or a similar example) that caused the search errors still?  I'm looking to reproduce the error so I can test any fixes I make.  So far I have failed to come up with a query which will produce an error but not be caught by the script's up front validation.
